/* ============================================================
   home.js — front page sections, in document order:

     preloader  five silhouettes take their positions
     hero       pinned; artwork resolves through its four passes
     award      trophy rises, kinetic type lands
     about      shape swaps per paragraph, masked line reveals
     wall       full-bleed mosaic, columns parallax in opposition
     portfolio  pinned horizontal track, pointer-driven reveal
     boards     clips play on hover, or in view on touch
     conform    pointer position drives saturation
   ============================================================ */

"use strict";

(() => {
  const { $, $$, MOTION, TOUCH, IS_FILE } = window.UZ;

  /* Position of each Lion team figure inside the artwork, normalised 0-1.
     Generated by tools/prep_v2.py into assets/sil-map.json, inlined here
     so no fetch is needed and the page works over file://. */
  const FIGURES = [
    { src: "assets/hero-sil-1.png", x: 0.03359, y: 0.05627, w: 0.15977, headX: 0.10781, headY: 0.05627 },
    { src: "assets/hero-sil-2.png", x: 0.22578, y: 0.09037, w: 0.14414, headX: 0.28594, headY: 0.09037 },
    { src: "assets/hero-sil-3.png", x: 0.38438, y: 0.05030, w: 0.15625, headX: 0.47422, headY: 0.05030 },
    { src: "assets/hero-sil-4.png", x: 0.56211, y: 0.09633, w: 0.18828, headX: 0.66914, headY: 0.09633 },
    { src: "assets/hero-sil-5.png", x: 0.78008, y: 0.05967, w: 0.20391, headX: 0.88594, headY: 0.05967 },
  ];

  /* Size the wordmark to the container: measure both words at a known
     size, then scale so they fill 86% of the width, leaving the rest as
     the gap. Re-runs on resize and once the display font has loaded. */
  const fitName = () => {
    const name = $(".hero__name");
    if (!name || window.innerWidth < 901) {
      if (name) name.style.fontSize = "";
      return;
    }
    const words = $$(".hero__word", name);
    if (words.length !== 2) return;

    name.style.fontSize = "100px";
    const natural = words.reduce((sum, w) => sum + w.getBoundingClientRect().width, 0);
    if (!natural) { name.style.fontSize = ""; return; }
    const target = name.clientWidth * 0.86;    /* the other 14% is the gap */
    name.style.fontSize = `${Math.min(240, (100 * target) / natural).toFixed(1)}px`;
  };

  /* ============================== HERO ============================== */
  const placeAnnos = () => {
    const frame = $(".hero__frame");
    if (!frame) return;
    const H = frame.offsetHeight;
    $$(".anno-item[data-fig]").forEach((item) => {
      const f = FIGURES[+item.dataset.fig];
      if (!f) return;
      item.style.setProperty("--x", `${(f.headX * 100).toFixed(3)}%`);
      item.style.setProperty("--b", `${((1 - f.headY) * 100).toFixed(3)}%`);
      const leader = $(".anno-item__leader", item);
      /* leader length is set from the head position, so labels end up in a
         ragged row above the artwork rather than a straight one */
      if (leader) leader.style.height = `${Math.max(14, (f.headY + 0.03) * H).toFixed(1)}px`;
    });
  };

  const typeOut = (el) => {
    const text = el.dataset.txt || (el.dataset.txt = el.textContent.trim());
    if (el.dataset.typed === "1") return;
    el.dataset.typed = "1";
    el.textContent = "";
    el.classList.add("typing");
    let i = 0;
    const step = () => {
      el.textContent = text.slice(0, ++i);
      if (i < text.length) setTimeout(step, 28 + Math.random() * 40);
      else el.classList.remove("typing");
    };
    step();
  };

  const initHero = () => {
    const hero = $(".hero");
    if (!hero) return;

    fitName();
    placeAnnos();
    window.addEventListener("resize", () => { fitName(); placeAnnos(); });
    if (document.fonts && document.fonts.ready) {
      document.fonts.ready.then(() => { fitName(); placeAnnos(); });
    }

    /* the marks draw on via stroke-dashoffset rather than fading in */
    const strokes = $$(".hero__annos .anno-shape > *");
    strokes.forEach((s) => {
      s.setAttribute("pathLength", "1");
      gsap.set(s, { strokeDasharray: 1, strokeDashoffset: 1 });
    });
    gsap.set(".anno-item", { opacity: 0, y: -10 });
    gsap.set(".anno-item__leader", { scaleY: 0 });
    gsap.set(".hero__paper", { opacity: 0 });
    gsap.set(".hero__pass--line", { clipPath: "inset(0% 100% 0% 0%)" });
    gsap.set(".hero__pass--flat", { clipPath: "inset(100% 0% 0% 0%)" });
    gsap.set(".hero__pass--final", { clipPath: "inset(0% 0% 0% 100%)" });

    const tl = gsap.timeline({
      defaults: { ease: "none" },
      scrollTrigger: {
        trigger: hero,
        start: "top top",
        /* a phone reads the resolve faster than a monitor does */
        end: () => (window.innerWidth < 901 ? "+=150%" : "+=190%"),
        pin: true, scrub: 0.6, anticipatePin: 1, invalidateOnRefresh: true,
      },
    });

    /* Settle the frame and dim the glow behind it. Any scale over 1 crops
       the artwork on a phone, so the push in and out is desktop-only. */
    const wide = () => window.innerWidth > 900;
    tl.fromTo(".hero__frame",
      { scale: () => (wide() ? 1.045 : 1) },
      { scale: 1, duration: 0.8 }, 0);
    tl.fromTo(".hero__lamp", { opacity: 1, scale: 1 }, { opacity: 0.32, scale: 1.1, duration: 0.55 }, 0.02);

    /* pass 1 -> 2: line wipes in left to right */
    tl.to(".hero__paper", { opacity: 1, duration: 0.1 }, 0.05);
    tl.to(".hero__pass--line", { clipPath: "inset(0% 0% 0% 0%)", duration: 0.2, ease: "power1.inOut" }, 0.05);
    tl.to(".hero__pass--sil", { opacity: 0.16, duration: 0.14 }, 0.1);

    /* labels draw on while the line pass is showing */
    $$(".hero__annos .anno-item").forEach((item, idx) => {
      const at = 0.2 + idx * 0.085;
      tl.to(item, { opacity: 1, y: 0, duration: 0.05 }, at);
      tl.to($(".anno-item__leader", item), { scaleY: 1, duration: 0.045 }, at + 0.01);
      const marks = $$("svg > *", item);
      if (marks.length) tl.to(marks, { strokeDashoffset: 0, duration: 0.05, stagger: 0.02 }, at + 0.02);
      const name = $(".anno-item__name", item);
      if (name) {
        tl.call(() => typeOut(name), null, at + 0.03);
        /* five names side by side won't fit a phone, so they take turns:
           each types out while its mark draws, then hands over to the next.
           classList in a tl.call — GSAP's className +=/-= syntax writes the
           literal operator string into the attribute instead of toggling. */
        if (window.innerWidth < 641) {
          tl.call(() => item.classList.add("is-active"), null, at);
          tl.call(() => item.classList.remove("is-active"), null, at + 0.1);
        }
      }
    });

    /* pass 2 -> 3: flats wipe in bottom to top */
    tl.to(".hero__pass--flat", { clipPath: "inset(0% 0% 0% 0%)", duration: 0.17, ease: "power2.inOut" }, 0.4);

    /* pass 3 -> 4: render wipes in right to left */
    tl.to(".hero__pass--final", { clipPath: "inset(0% 0% 0% 0%)", duration: 0.2, ease: "power2.inOut" }, 0.62);
    tl.to(".hero__pass--sil", { opacity: 0, duration: 0.08 }, 0.62);

    /* wordmark parallax, then the frame scales past the viewport on exit */
    tl.to(".hero__name", { yPercent: -18, duration: 1 }, 0);
    tl.to(".hero__base", { opacity: 0, duration: 0.12 }, 0.72);
    tl.to(".hero__frame", { scale: () => (wide() ? 1.16 : 1), duration: 0.2, ease: "power2.in" }, 0.82);
    tl.to(".hero__annos", { opacity: 0, duration: 0.12 }, 0.84);
  };

  const heroEntrance = () => {
    if (!MOTION) return;
    gsap.from(".hero__word span", {
      yPercent: 118, opacity: 0, duration: 1.15, ease: "expo.out", stagger: 0.035,
    });
    gsap.from(".hero__meta, .hero__base", { opacity: 0, duration: 1.1, delay: 0.35, ease: "power2.out" });
  };

  /* ============================== AWARD ============================== */
  const initAward = () => {
    const section = $(".award");
    if (!section) return;
    const img = $(".award__trophy-img");

    const tl = gsap.timeline({
      defaults: { ease: "none" },
      scrollTrigger: {
        trigger: section, start: "top top", end: "+=120%",
        pin: true, scrub: 0.5, anticipatePin: 1, invalidateOnRefresh: true,
      },
    });

    tl.fromTo(img,
      { yPercent: 64, rotate: -9, opacity: 0, scale: 0.92 },
      { yPercent: 0, rotate: 0, opacity: 1, scale: 1, duration: 0.4, ease: "expo.out" }, 0.04);
    tl.fromTo(".award__bloom", { opacity: 0, scale: 0.6 }, { opacity: 1, scale: 1, duration: 0.3 }, 0.04);
    tl.fromTo(".award__ghost", { opacity: 0, x: 80 }, { opacity: 0.14, x: 0, duration: 0.35 }, 0.02);

    [["--1", 0.26], ["--2", 0.33], ["--3", 0.4]].forEach(([mod, at]) => {
      tl.fromTo(`.award__line${mod} .display`,
        { yPercent: 115 }, { yPercent: 0, duration: 0.08, ease: "expo.out" }, at);
    });

    tl.fromTo(".award__caa", { opacity: 0, y: 16 }, { opacity: 1, y: 0, duration: 0.08 }, 0.5);
    tl.fromTo(".award__rule", { scaleX: 0 }, { scaleX: 1, duration: 0.1, ease: "power2.inOut" }, 0.58);

    /* tilt the trophy with scroll velocity */
    ScrollTrigger.create({
      trigger: section, start: "top bottom", end: "bottom top",
      onUpdate: (self) => {
        const v = gsap.utils.clamp(-8, 8, self.getVelocity() / 280);
        gsap.to(img, { rotation: v, duration: 0.6, overwrite: "auto" });
      },
    });
  };

  /* ============================== ABOUT ============================== */
  const initAbout = () => {
    const paras = $$(".about__flow .prose");
    if (!paras.length) return;

    const labels = ["SQUARE / RIGID", "TRIANGLE / AGGRESSION", "CIRCLE / FRIENDLINESS"];
    const shapes = [$(".about__shape-sq"), $(".about__shape-tri"), $(".about__shape-cir")].filter(Boolean);
    const labelEl = $(".about__shape-label");

    shapes.forEach((s, i) => gsap.set(s, { opacity: i === 0 ? 1 : 0, scale: i === 0 ? 1 : 0.55, rotate: i === 0 ? 0 : -30 }));

    paras.forEach((p, i) => {
      window.UZ.revealLines(p, 0.055);
      ScrollTrigger.create({
        trigger: p, start: "top 62%", end: "bottom 62%",
        onToggle: (self) => {
          if (!self.isActive) return;
          const idx = i % 3;
          shapes.forEach((s, k) => gsap.to(s, {
            opacity: k === idx ? 1 : 0,
            scale: k === idx ? 1 : 0.55,
            rotate: k === idx ? 0 : -30,
            duration: 0.7, ease: "power3.out",
          }));
          if (labelEl) labelEl.textContent = labels[idx];
        },
      });
    });
  };

  /* ============================== WALL ============================== */
  /* Every finished artwork, tiled edge to edge — the gallery wall the
     client asked for. Every tile opens full size in the viewer; hover
     lifts the colour and reveals the sheet's name. */
  /* [slug, ratio, title, project, full-res] — the ratio is declared so
     each column has its full height before any image loads */
  const WALL = [
    ["eow/eow-01-lineup", 1.899, "The sheet", "Eyes of Wakanda", "assets/eow/eow-01-lineup.png"],
    ["eow/eow-02-noni", 1.818, "Noni", "Eyes of Wakanda", "assets/eow/eow-02-noni.png"],
    ["eow/eow-03-noni-keys", 1.765, "Noni — costume keys", "Eyes of Wakanda", "assets/eow/eow-03-noni-keys.png"],
    ["eow/eow-04-old-noni", 1.779, "Noni, older", "Eyes of Wakanda", "assets/eow/eow-04-old-noni.png"],
    ["eow/eow-05-traveller", 1.364, "The traveller", "Eyes of Wakanda", "assets/eow/eow-05-traveller.png"],
    ["eow/eow-06-councilman", 1.452, "High councilman", "Eyes of Wakanda", "assets/eow/eow-06-councilman.png"],
    ["eow/eow-07-kuda", 1.301, "Kuda", "Eyes of Wakanda", "assets/eow/eow-07-kuda.png"],
    ["eow/eow-08-tafari", 0.888, "Tafari and Kuda", "Eyes of Wakanda", "assets/eow/eow-08-tafari.png"],
    ["eow/eow-09-lion-guard", 1.011, "Lion guards — faces", "Eyes of Wakanda", "assets/eow/eow-09-lion-guard.png"],
    ["eow/eow-10-chainmakers", 2.256, "Lion chain makers", "Eyes of Wakanda", "assets/eow/eow-10-chainmakers.png"],
    ["eow/eow-11-harem", 1.915, "Harem captives", "Eyes of Wakanda", "assets/eow/eow-11-harem.png"],
    ["eow/eow-12-seamstresses", 1.226, "Seamstresses", "Eyes of Wakanda", "assets/eow/eow-12-seamstresses.png"],
    ["eow/eow-13-ethiopian", 1.297, "Ethiopian soldiers", "Eyes of Wakanda", "assets/eow/eow-13-ethiopian.png"],
    ["eow/eow-14-crowd", 1.347, "River tribe", "Eyes of Wakanda", "assets/eow/eow-14-crowd.png"],
    ["eow/eow-15-dora", 1.965, "Shape language — the Lion team", "Eyes of Wakanda", "assets/eow/eow-15-dora.png"],
    ["eow/eow-16-flashback", 1.325, "Flashback — render test", "Eyes of Wakanda", "assets/eow/eow-16-flashback.png"],
    ["eow/eow-17-dora-02", 1.829, "Lion team — in character", "Eyes of Wakanda", "assets/eow/eow-17-dora-02.png"],
    ["eow/eow-18-crowd-02", 1.531, "Mining tribe", "Eyes of Wakanda", "assets/eow/eow-18-crowd-02.png"],
    ["eow/eow-19-crowd-03", 1.625, "Wakandan caravan — merchant tribe", "Eyes of Wakanda", "assets/eow/eow-19-crowd-03.png"],
    ["iyanu/iyanu-01-ideation", 1.642, "The sheet", "Iyanu", "assets/iyanu/iyanu-01-ideation.jpg"],
    ["iyanu/iyanu-02-exploration", 2.284, "Exploration — colour and line", "Iyanu", "assets/iyanu/iyanu-02-exploration.jpg"],
    ["iyanu/iyanu-03-exploration", 1.642, "Exploration — second pass", "Iyanu", "assets/iyanu/iyanu-03-exploration.jpg"],
    ["iyanu/iyanu-04-biyi", 1.329, "Biyi — action", "Iyanu", "assets/iyanu/iyanu-04-biyi.jpg"],
    ["iyanu/iyanu-05-biyi-02", 1.2, "Biyi — model sheet", "Iyanu", "assets/iyanu/iyanu-05-biyi-02.jpg"],
    ["iyanu/iyanu-06-0621", 1.064, "Height chart", "Iyanu", "assets/iyanu/iyanu-06-0621.jpg"],
    ["iyanu/iyanu-07-0621-02", 0.881, "The archer", "Iyanu", "assets/iyanu/iyanu-07-0621-02.jpg"],
    ["personal/personal-01-afro-ninja", 1.0, "Afro ninja", "Personal", "assets/personal/personal-01-afro-ninja.png"],
    ["personal/personal-02-pirate", 1.779, "Pirate boy, action poses", "Personal", "assets/personal/personal-02-pirate.png"],
    ["personal/personal-03-vampire", 1.779, "Vampire", "Personal", "assets/personal/personal-03-vampire.png"],
    ["personal/personal-04-femme", 2.0, "Femme fatale", "Personal", "assets/personal/personal-04-femme.png"],
    ["personal/personal-05-hands", 2.0, "Hands", "Personal", "assets/personal/personal-05-hands.png"],
    ["personal/personal-06-people", 2.0, "People", "Personal", "assets/personal/personal-06-people.png"],
    ["personal/personal-07-mammal", 2.0, "Mammal college", "Personal", "assets/personal/personal-07-mammal.png"],
    ["personal/personal-08-gangster", 1.002, "Female gangster", "Personal", "assets/personal/personal-08-gangster.png"],
    ["personal/personal-09-sketches", 1.0, "Character sketches", "Personal", "assets/personal/personal-09-sketches.jpg"],
    ["personal/personal-10-dump", 0.999, "Style dump", "Personal", "assets/personal/personal-10-dump.jpg"],
    ["personal/personal-11-futuristic", 1.0, "Futuristic guy", "Personal", "assets/personal/personal-11-futuristic.png"],
    ["personal/personal-12-sketch", 1.0, "Sketches", "Personal", "assets/personal/personal-12-sketch.png"],
    ["boards/coma-toes-f02", 1.333, "Coma Toes — panel 2", "Storyboards", "assets/thumbs/boards/coma-toes-f02.jpg"],
    ["boards/coma-toes-f05", 1.333, "Coma Toes — panel 5", "Storyboards", "assets/thumbs/boards/coma-toes-f05.jpg"],
    ["boards/coma-toes-f07", 1.333, "Coma Toes — panel 7", "Storyboards", "assets/thumbs/boards/coma-toes-f07.jpg"],
    ["boards/cash-trapped-a-f03", 1.779, "Cash Trapped I — panel 3", "Storyboards", "assets/thumbs/boards/cash-trapped-a-f03.jpg"],
    ["boards/cash-trapped-a-f07", 1.779, "Cash Trapped I — panel 7", "Storyboards", "assets/thumbs/boards/cash-trapped-a-f07.jpg"],
    ["boards/cash-trapped-b-f02", 1.779, "Cash Trapped II — panel 2", "Storyboards", "assets/thumbs/boards/cash-trapped-b-f02.jpg"],
    ["boards/cash-trapped-b-f05", 1.779, "Cash Trapped II — panel 5", "Storyboards", "assets/thumbs/boards/cash-trapped-b-f05.jpg"],
  ];

  const initWall = () => {
    const host = $(".wall__cols");
    if (!host) return;

    const colCount = () => {
      const w = window.innerWidth;
      if (w >= 1700) return 6;
      if (w >= 1280) return 5;
      if (w >= 900) return 4;
      if (w >= 600) return 3;
      return 2;
    };

    let built = 0;
    let triggers = [];

    /* the wall is a full scrolling gallery: its height comes from the
       columns' natural content, minus the drift headroom */
    const sizeWall = () => {
      const wall = $(".wall");
      if (!window.matchMedia("(min-width: 901px)").matches) {
        wall.style.height = "";
        return;
      }
      const colsEls = host.querySelectorAll(".wall__col");
      if (!colsEls.length) return;
      const colW = host.clientWidth / colsEls.length;
      let maxH = 0;
      colsEls.forEach((c) => {
        let h = 0;
        c.querySelectorAll(".wall__tile img").forEach((im) => {
          h += colW / (parseFloat(im.style.aspectRatio) || 1.5) + 3;
        });
        maxH = Math.max(maxH, h);
      });
      wall.style.height = `${Math.round(Math.max(maxH * 0.92, window.innerHeight))}px`;
    };

    const build = () => {
      const cols = colCount();
      if (cols === built) return;
      built = cols;

      triggers.forEach((t) => t.kill());
      triggers = [];
      host.textContent = "";
      host.style.gridTemplateColumns = `repeat(${cols}, 1fr)`;

      const buckets = Array.from({ length: cols }, () => {
        const c = document.createElement("div");
        c.className = "wall__col";
        host.appendChild(c);
        return c;
      });

      /* round-robin, so neighbouring tiles are from different projects */
      WALL.forEach(([slug, ratio, title, project, full], i) => {
        const tile = document.createElement("button");
        tile.type = "button";
        tile.className = "wall__tile";
        tile.dataset.plate = full;
        tile.dataset.title = title;
        tile.dataset.no = String(i + 1).padStart(2, "0");
        tile.setAttribute("aria-label", `${title} — ${project}. Open full size.`);

        const im = document.createElement("img");
        if (!IS_FILE) im.loading = "lazy";   /* file:// never fires lazy loads */
        im.decoding = "async";
        im.alt = `${title} — ${project}`;
        im.style.aspectRatio = String(ratio);
        im.src = `assets/thumbs/${slug}.jpg`;

        const cap = document.createElement("span");
        cap.className = "wall__cap";
        cap.setAttribute("aria-hidden", "true");
        const t = document.createElement("span");
        t.className = "wall__cap-title";
        t.textContent = title;
        const p = document.createElement("span");
        p.className = "wall__cap-project";
        p.textContent = project;
        cap.append(t, p);

        tile.append(im, cap);
        buckets[i % cols].appendChild(tile);
      });

      sizeWall();

      if (!MOTION) return;

      /* cold while approaching, warms as the wall fills the viewport */
      const warm = ScrollTrigger.create({
        trigger: ".wall", start: "top 55%", end: "bottom 45%",
        toggleClass: { targets: ".wall", className: "is-warm" },
      });
      triggers.push(warm);

      /* drift is desktop-only: on a phone the wall scrolls like a gallery
         and columns must stay in normal flow */
      if (window.matchMedia("(min-width: 901px)").matches) {
        /* Drift is measured against the viewport, not the column. A column
           is several thousand pixels tall and a percentage of that pushes
           its images off screen entirely. */
        const drift = () => window.innerHeight * 0.22;

        buckets.forEach((col, i) => {
          const dir = i % 2 ? 1 : -1;
          const rate = 0.6 + (i % 3) * 0.35;
          const tw = gsap.fromTo(col,
            { y: () => dir * drift() * rate },
            {
              y: () => -dir * drift() * rate, ease: "none",
              scrollTrigger: {
                trigger: ".wall", start: "top bottom", end: "bottom top",
                scrub: 0.8, invalidateOnRefresh: true,
              },
            });
          if (tw.scrollTrigger) triggers.push(tw.scrollTrigger);
        });
      }
    };

    build();

    let resizeTimer = 0;
    window.addEventListener("resize", () => {
      clearTimeout(resizeTimer);
      resizeTimer = setTimeout(() => { build(); sizeWall(); ScrollTrigger.refresh(); }, 220);
    });
  };

  /* ============================== PORTFOLIO ============================== */
  const initPortfolio = () => {
    const track = $(".portfolio__track");
    if (!track) return;

    /* a circular reveal of the line pass follows the pointer */
    $$(".work-card__media").forEach((media) => {
      const xray = $(".work-card__img--xray", media);
      const probe = $(".work-card__probe", media);
      if (!xray) return;

      let r = 0, target = 0, raf = 0;
      const maxR = () => {
        const b = media.getBoundingClientRect();
        return Math.max(b.width, b.height) * 0.42;
      };
      const tick = () => {
        r += (target - r) * 0.16;
        if (Math.abs(target - r) < 0.5) r = target;
        xray.style.clipPath = `circle(${r.toFixed(1)}px at var(--mx, 50%) var(--my, 50%))`;
        if (probe) {
          probe.style.width = probe.style.height = `${(r * 2).toFixed(1)}px`;
          probe.style.opacity = r > 4 ? 0.5 : 0;
        }
        if (r !== target) raf = requestAnimationFrame(tick);
      };
      const aim = (x, y) => {
        const b = media.getBoundingClientRect();
        media.style.setProperty("--mx", `${(x - b.left).toFixed(1)}px`);
        media.style.setProperty("--my", `${(y - b.top).toFixed(1)}px`);
      };
      const open = (x, y) => { aim(x, y); target = maxR(); cancelAnimationFrame(raf); raf = requestAnimationFrame(tick); };
      const shut = () => { target = 0; cancelAnimationFrame(raf); raf = requestAnimationFrame(tick); };

      media.addEventListener("pointermove", (e) => { if (!media.dataset.pinned) open(e.clientX, e.clientY); });
      media.addEventListener("pointerleave", shut);

      if (TOUCH) {
        media.addEventListener("click", (e) => {
          if (!media.dataset.pinned) {
            e.preventDefault();                 /* first tap reveals */
            media.dataset.pinned = "1";
            open(e.clientX, e.clientY);
          } else {
            delete media.dataset.pinned;        /* second tap follows the link */
            shut();
          }
        });
      }
    });

    if (!MOTION) return;

    const mm = gsap.matchMedia();
    mm.add("(min-width: 901px)", () => {
      const metas = $$(".work-card__meta");
      const dist = () => Math.max(0, track.scrollWidth - document.documentElement.clientWidth + 48);

      gsap.to(track, {
        x: () => -dist(), ease: "none",
        scrollTrigger: {
          trigger: ".portfolio", start: "top top", end: () => `+=${dist() * 1.1}`,
          pin: true, scrub: 1, invalidateOnRefresh: true, anticipatePin: 1,
        },
      });

      /* captions travel slightly faster than the artwork */
      gsap.to(metas, {
        x: () => -0.06 * dist(), ease: "none",
        scrollTrigger: {
          trigger: ".portfolio", start: "top top", end: () => `+=${dist() * 1.1}`,
          scrub: 1, invalidateOnRefresh: true,
        },
      });
    });
  };

  /* ============================== BOARDS ============================== */
  const initBoards = () => {
    $$(".board-tile").forEach((tile) => {
      const video = $("video", tile);
      if (!video) return;

      const play = () => {
        tile.classList.add("is-playing");
        const p = video.play();
        if (p && p.catch) p.catch(() => tile.classList.remove("is-playing"));
      };
      const stop = () => { tile.classList.remove("is-playing"); video.pause(); video.currentTime = 0; };

      if (TOUCH) {
        /* no hover on touch: play while the tile is on screen */
        if (MOTION) {
          ScrollTrigger.create({
            trigger: tile, start: "top 70%", end: "bottom 30%",
            onEnter: play, onEnterBack: play, onLeave: stop, onLeaveBack: stop,
          });
        }
      } else {
        tile.addEventListener("pointerenter", play);
        tile.addEventListener("pointerleave", stop);
        tile.addEventListener("focus", play);
        tile.addEventListener("blur", stop);
      }
    });
  };

  /* ============================== CREATE / CONFORM ============================== */
  const initConform = () => {
    const section = $(".conform");
    if (!section || !MOTION) return;

    const tint = $(".conform__tint");
    const marks = $$(".conform__marks svg");
    const line = $(".conform__line");
    const wordL = $(".conform__side--left");
    const wordR = $(".conform__side--right");
    const mix = { v: 0.5 };

    const scatter = [], rigid = [];
    const measure = () => {
      const W = section.clientWidth, H = section.clientHeight;
      const sc = [[16, 22], [72, 18], [28, 68], [62, 76], [46, 44]];
      const rg = [[32, 50], [41, 50], [50, 50], [59, 50], [68, 50]];
      sc.forEach(([px, py], i) => { scatter[i] = { x: (W * px) / 100 - W / 2, y: (H * py) / 100 - H / 2 }; });
      rg.forEach(([px, py], i) => { rigid[i] = { x: (W * px) / 100 - W / 2, y: (H * py) / 100 - H / 2 }; });
    };
    measure();
    window.addEventListener("resize", measure);

    gsap.set(marks, { left: "50%", top: "50%", xPercent: -50, yPercent: -50 });

    const art = $(".conform__art");

    const apply = () => {
      const m = mix.v;
      section.style.filter = `grayscale(${(1 - m).toFixed(3)})`;
      if (art) art.style.opacity = (0.3 + 0.34 * m).toFixed(3);
      tint.style.opacity = (0.2 * m).toFixed(3);
      line.style.letterSpacing = `${(0.02 + 0.12 * m).toFixed(3)}em`;
      wordL.style.opacity = (1 - m).toFixed(3);
      wordR.style.opacity = m.toFixed(3);
      marks.forEach((el, i) => {
        const s = scatter[i], r = rigid[i];
        gsap.set(el, {
          x: r.x + (s.x - r.x) * m,
          y: r.y + (s.y - r.y) * m,
          rotation: m * (i * 19 - 38),
          scale: 1 + m * 0.5,
        });
      });
    };
    apply();

    if (TOUCH) {
      gsap.to(mix, { v: 1, duration: 4.5, ease: "sine.inOut", yoyo: true, repeat: -1, repeatDelay: 1.4, onUpdate: apply });
    } else {
      const setMix = gsap.quickTo(mix, "v", { duration: 0.7, ease: "power2.out", onUpdate: apply });
      section.addEventListener("pointermove", (e) => {
        const b = section.getBoundingClientRect();
        setMix(gsap.utils.clamp(0, 1, (e.clientX - b.left) / b.width));
      });
      section.addEventListener("pointerleave", () => setMix(0.5));
    }
  };

  /* ============================== INIT ============================== */
  window.UZ.boot();

  if (MOTION) {
    initHero();
    initAward();
    initAbout();
    initPortfolio();
    initBoards();
    initConform();
  } else {
    initBoards();
  }

  initWall();
  window.UZ.initPreloader(FIGURES, heroEntrance);
})();
