hero_lead: Emmy & CAA Award-winning
hero_rest: Visual Development Artist and Writer/Director in Animation
email: uzomadunkwu@gmail.com
footer_clients:
  - Marvel Animation
  - Lion Forge
  - Netflix Animation
  - Disney
  - Laika
  - Triggerfish
  - Psyop
  - Stoopid Buddy Stoodios
  - Scroll Entertainment
credit_text: ZM3 Limited
credit_url: https://zm3.ng/
